apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-demo-test-app
  template:
    metadata:
      labels:
        app: cicd-demo-test-app 
    spec:
      containers:
        - name: cicd-demo-test-ap
          image: public.ecr.aws/s6y5a7e8/voucher-app:v10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: cicd-demo-test-app 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
